name: CAD Pipeline

on:
  push:
    paths:
      - "*.STEP"  # Trigger on any changes to STEP files
      - 'geometry_check.py'
      - '.github/workflows/**'


jobs:
  validate-step-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate STEP File
        run: |
          echo "Validating cdp_latest.STEP..."
          # Mock validation logic (replace with actual validation script)
          if [ ! -f cdp_latest.STEP ]; then
            echo "STEP file not found!"
            exit 1
          fi
          echo "Validation successful for cdp_latest.STEP."

  validate-geometry:
    needs: validate-step-file
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check directory contents
      run: |
        echo "📂 Directory listing before running FreeCAD:"
        ls -la

    - name: Setup FreeCAD with Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: base
        environment-file: environment.yml
        auto-activate-base: true

    - name: Install FreeCAD
      run: |
        sudo apt-get update
        sudo apt-get install -y freecad freecad-common

    - name: Run geometry check
      run: |
        echo "▶️ Running geometry_check.py..."
        freecadcmd geometry_check.py


  convert-step-to-gltf:
    needs: validate-step-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Convert STEP to GLTF
        run: |
          echo "Converting cdp_latest.STEP to cdp_latest.gltf..."
          # Mock conversion logic (replace with actual conversion command)
          cp cdp_latest.STEP cdp_latest.gltf  # Simulating conversion

  deploy-converted-model:
    needs: convert-step-to-gltf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy Converted GLTF Model
        run: |
          echo "Deploying cdp_latest.gltf to server..."
          # Mock deployment logic (replace with actual deployment command)
          echo "Deployment successful! (mock)"

